#!/bin/bash

#Going to user's home directory first
cd ~

#check if ".bashrc" file exists in the user's home directory 
if [ -e /home/shaher/.bashrc ]; then
	echo ".bashrc file exists in the user's home directory"
	#create global variable "HOME" with value of "HOSTNAME"
	echo "export HELLO=$HOSTNAME" >> .bashrc
	echo "LOCAL=whoami" >> .bashrc
#if the ".bashrc" file does not exist, do nothing 
else
	echo ".bashrc file does not exist"
fi

#Opening new terminal from the current terminal
gnome-terminal 
